version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chat_app
hooks:
  BeforeInstall:
    - location: scripts/Stop_Server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/Start_Server.sh
      timeout: 300
      runas: root
